### PR TITLE
fix segment-gcp crashes with simple configuration

### LINKED ISSUE #407: google cloud project detecter crashes with simple configuration
**Describe the bug**
If the active gcloud configuration file has a [core] section and there is no project key in it, the GCP segment will panic with a slice bounds out of range error. This occurs because the code does not handle parsing the simplest property files gracefully.

This PR fixes this panic and refactors the project discovery logic for efficiency.

**To Reproduce**
Create a minimal gcloud configuration structure. For example
```
[core] 
account = 0deltast@gmail.com 
project = zdelta-test 
```

Run powerline-go in a shell. The program will panic.
**Expected behavior**
powerline-go should correctly display the project without crashing.

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04 with WSL2 (Win11)
 - Architecture: intel
 - Shell: fish

...But it will occur in all environments.

**Additional context**

### PR DESCRIPTION
**Pull request by 0Delta**
fix #407

### CODE REVIEW

File: segment-gcp.go [hunk 1]
```diff
@@ -95,7 +94,7 @@ func getGCPProjectFromFile() (string, error) {
 		b = b[:coreEnd]
 	}
 
-	lines := bytes.Split(b[coreStart+len(gcloudCoreSectionHeader):coreEnd], []byte("\n"))
+	lines := bytes.Split(b[coreStart+len(gcloudCoreSectionHeader):], []byte("\n"))
```
Comment (0Delta) [inline segment-gcp.go:97]: We cannot use `-1` as an array index in golang.
Also, if the case requires processing, it is truncated in the previous line, so processing should not be necessary here.

File: segment-gcp.go [hunk 2]
```diff
@@ -37,7 +36,7 @@ func getActiveGCloudConfig(configDir string) (string, error) {
 		return "", err
 	}
 
-	contents, err := ioutil.ReadFile(activeConfigPath)
+	contents, err := os.ReadFile(activeConfigPath)
```
Comment (0Delta) [inline segment-gcp.go:39]: Since `ioutil.ReadFile` is obsolete, use `os.ReadFile`
